### ISSUE TITLE
Warnings for meaningless code

### ISSUE THREAD

**Issue by Y-Less** [pawn-lang/compiler#172]
```pawn
Func(const &var)
{
}
```

If you modify the variable in the function you will get an error.  If you don't, why is it a reference?  The combination is currently allowed but silly.  Similarly:

```pawn
Func(const ...)
{
}
```

That is allowed by the compiler, but is probably even worse - the `const` is totally ignored.  You can pass `const` variables when it isn't there, or modify variables via `setarg` when it is there.  I don't actually know what the best solution to that would be because obviously `setarg` is pretty much a total compiler bypass.

Probably just warnings for those `const`s that they are meaningless.

**Comment by YashasSamaga** [comment]
Would this be meaningless?

`static const k;`

The behavior of the above is well defined. The compiler initializes the value to zero.

**Comment by Y-Less** [comment]
How is that related?  I'm talking about the use of both `const` - value can't be modified, and `&` - source value will be modified, together.  Basically `const &` says "this value can't be modified, and any modifications are propagated".

**Comment by YashasSamaga** [comment]
I thought of using this issue to discuss other kinds of meaningless code instead of having different issues for each.

**Comment by Y-Less** [comment]
I actually found a use for `const &` since writing this:

```pawn
ModifyConst(const & var, val)
{
    setarg(0, val);
}
```

Or course, since I just argued against not modifying the language for the sake of maintaining compatibility with awkward workaround code, in the rare case where this is desired the warning can be disabled and re-enabled:

https://github.com/Open-GTO/sa-mp-fixes/blob/c4eda3041f2935dad7ddae7c8a3892a29781974c/fixes.inc#L12015-L12026

On your issue.  Valueless variables are very well defined and widely as `0` in PAWN everywhere.  I don't think `static const x;` in any way goes against that.

**Comment by Y-Less** [comment]
As for what the warning should be, something like "incompatible combination of class specifiers".  Error 42 is "invalid combination of class specifiers", this isn't quite invalid, I don't even like the word "incompatible", but something alliteratively similar but with slightly less connotation of being totally wrong.  "Unlikely", "ignored", "meaningless", or something else like that.

**Comment by YashasSamaga** [comment]
```
func1(const ...) { }
func2(const& x) { }
func3(const x) { }
func4(...) { }
func5(&x) { }
func6(x) { }
main ()
{
	new a = 5;
	func1(a);
	func2(a);
	func3(a);
	func4(a);
	func5(a);
	func6(a);
}
```

```
test.pwn(1) : warning 238: meaningless combination of class specifiers (const variable arguments)
test.pwn(2) : warning 238: meaningless combination of class specifiers (const reference)
```
