### ISSUE TITLE
redundant pragma deprecated warning at the site of declaration

### ISSUE THREAD

**Issue by YashasSamaga** [pawn-lang/compiler#242]
```
#pragma deprecated don't use please
f() {

}

main() {
  
}
```
no deprecated function warning for the above code which is right
```
#pragma deprecated don't use please
f() {

}

main() {
  f();
}
```
two warnings are thrown instead of just one

I think this is not right. : the warning thrown at the site of declaration of the deprecated function is redundant.

**Comment by YashasSamaga** [comment]
The fix is as simple as deleting one line: [`error(234,symbolname,ptr);  /* deprecated (probably a public function) */`](https://github.com/Southclaws/pawn/blob/master/source/compiler/sc1.c#L3692)

It appears like it has been intentionally kept to trigger warnings at the site of declaration.

**Comment by Southclaws** [comment]
I'm down for removing this - it makes little sense to trigger a warning at the decl because the person seeing this error is most likely a library consumer, not the author so they are more concerned about their own code rather than the library that provides that API.

**Comment by Zeex** [comment]
I think this is supposed to handle cases when a forward declaration is marked as deprecated and somebody declares a (public?) function with the same name/prototype.

```pawn
#include <a_samp>

#pragma deprecated
forward hello();

public hello() {
	print("I'm deprecated!");
}

main() {
}
```

**Comment by Y-Less** [comment]
Seems this isn't solved, I thought it was.
