### ISSUE TITLE
Variadic arguments passed by value

### ISSUE THREAD

**Issue by samphunter** [pawn-lang/compiler#277]
I was trying to use the new emit operator to create system for making function pointers. I got to the point of having this:
```C
#define GetFunc(%0) Func:emit(const.pri %0)
stock CallFunc(Func:f, ...) {
	#pragma unused f, a
	emit {
	    load.s.alt 12
	    load.s.pri 8
	    add.c -4
	    stor.s.pri 12
	    load.s.pri 4
	    stor.s.pri 8
	    load.s.pri 0
	    sctrl 5
	    xchg
	    stack 8
	    sctrl 6
 	}
}
```
This seems to work, but the function must use arguments passed by reference, because ... passes everything by reference. It would be nice for this and other use-cases (natives for example) to have a variadic argument system that would pass cells by value.

I have no good idea, how it would be denoted though.

**Comment by Y-Less** [comment]
How would you retrieve them?  `getarg` expects pointers.  And how would you distinguish arrays, which must be by reference always?

Anyway, a whole library for what you are trying to do:

https://github.com/Y-Less/indirection

**Comment by samphunter** [comment]
> How would you retrieve them? getarg expects pointers. 
Using emit and in plugins.
> And how would you distinguish arrays, which must be by reference always?
The same way I distinguish them now? There still has to be some external method of distinguishing strings/arrays from cells in both plugins and pawn.

IMHO, considering how slow getarg() is, it is not even usable for strings and arrays anyway.

> Anyway, a whole library for what you are trying to do
Nice. Did not know that. 

But then again, mine is a lightweight wrapper with 12 instructions overhead. Yours looks much more complicated.

**Comment by YashasSamaga** [comment]
> >    And how would you distinguish arrays, which must be by reference always?
> 
> The same way I distinguish them now? There still has to be some external method of distinguishing strings/arrays from cells in both plugins and pawn.

How are you distinguishing them now?

It is not possible to find out which arguments are pass-by-value or pass-by-reference or anything along those lines because the stack consists of just cells. The value stored in the cells can be an address or a value or whetever. It is not possible to tell whether it is an address or not.

Most of the functions which use variable arguments take information about the argument types through some other argument (format string in case of printf).

**Comment by samphunter** [comment]
> Most of the functions which use variable arguments take information about the argument types through some other argument (format string in case of printf).

Exactly what I was talking about. I have to use this anyway, so it does not matter, whether the cells are references, or values. I can distinguish them using the same mechanism, just adding let's say r for references to cells.

> I also don't see how this could be useful. It would complicate the code. How do you decide what is passed by value and what is passed by reference? This would require new syntax.

Of course I was suggesting a new syntax. Changing the behavior would be practically impossible. And as for how I would use it, there is one example right in the original post. Another use would be in my plugin, and another could be using a macro to redirect functions to other public functions (to provide default arguments, and at the same time make the function public).

And those are just thinks I would use right away, there probably are more possibilities with this.

**Comment by Y-Less** [comment]
So what would this new syntax be?

**Comment by YashasSamaga** [comment]
@samphunter I did not understand any of the applications you stated. Why can't references be used for everything? What's the need to pass arguments by value?

I also can't think of any decent syntax yo achieve this. How should the compiler decide whether something has to be passes by value or reference?

**Comment by samphunter** [comment]
> So what would this new syntax be?

> I also can't think of any decent syntax to achieve this. How should the compiler decide whether something has to be passes by value or reference?

I can't think of anything good right now, but the general idea is, that it would be something like ,,, 
So you could choose, whether your function will take cells by reference using ... or by value using ,,,

> I did not understand any of the applications you stated. Why can't references be used for everything? What's the need to pass arguments by value?

In the most important use-case, the one I shown in the first post, to use references, I would have to make all functions use references. So lets say I would want this kind of code:

```C
SomeFunction(a, b[]) {
    
}
...
new Func:f = GetFunc(SomeFunction);
...
CallFunction(f, 11);
```

This would not work, I would have to change some function to use reference, like: `SomeFunction(&a, b[])`. This would make it both, hardly readable (How to distinguish, whether the function actualy changes the value) and problematic (I am suddenly giving it a literal as reference).

**Comment by Y-Less** [comment]
Strings are passed by reference, as are reference arguments.  Cells are (sometimes) passed by value.  You are claiming this will remove the need to distinguish between strings and variables, but it demonstrably won't, by your own argument.  If you can pass both values and references to it, there needs to be a way to distinguish which is which at the call site statically at compile time:

```
new str[5];
MyMagicFunc(str[2]);
```

Is that the value at `str[2]`, a reference to the cell at `str[2]`, or the string starting at `str[2]`?  The syntax doesn't tell us.

```
new a;
MyMagicFunc(a);
```

Is that a value or a reference?

```
MyMagicFunc(5);
```

Is that a value, or a literal passed to what should be a reference, and thus needs heap allocation and cleanup?

There is literally no way to determine what should be passed as value and what should be passed by reference.  That's why `...` does everything the same and why things like specifier strings exist, so that when a whole load of generic data comes in, you know what they mean.

**Comment by Y-Less** [comment]
```
Func1(a, b[]) {
    
}

Func2(&a, b[]) {
    
}
...
new Func:f = condition ? GetFunc(Func1) : GetFunc(Func2);
...
new a = 11;
CallFunction(f, a, "hello");
```

How should `a` be passed?

And again, there is a whole library to do this already (and the type safety is the reason it is more complex than your version, as you rightly pointed out).  So you are asking for impossible features to implement something that can (and has) already been done without them.

**Comment by samphunter** [comment]
@Y-Less I am not sure, if you understand, what I am asking. I am not asking to make it possible to mix references and values. I am just asking for a version of ... that would pass all cells as values.

And I provided the example with CallLocalFunction. CallLocalFunction does not need to know, how to use the arguments, because it does not use them. It just needs to pass them along. The public it calls knows how to handle them.

In your example, `Func2(&a, b[])` would not be callable using `CallFunction`, but that does not matter to me. As for your library. It is a nice thing for a niche use, but I can't afford the overhead of processing the arguments for every call in my use of it.

**Comment by samphunter** [comment]
Okey, I did not think of this `MyMagicFunc(str[2]);`.
I want to say value, because of how C works, but I get that this is something, that would be unclear in PAWN.

Well I guess my only other option is to make a separate version of CallFunc for every combination of arguments I will use, even though the function will do exactly the same thing... I just can't afford the overhead of your library in my code, and the safety is not something I really need.
