### ISSUE TITLE
File created at c:\* on any compile.

### ISSUE THREAD

**Issue by rt-2** [pawn-lang/compiler#280]
Hi,
For me, every time I compile, there is a copy of the file that is wrongly created on c:\ directly.
Thank you,
rt-2

**Comment by Dayvison** [comment]
This happens when you not define the output file

**Comment by rt-2** [comment]
Yes thank you.
In the compiler options in Pawno, the field "copy script to" was "/".
I couldn't leave it empty so I put "./" in it and it seems to work.
Thank you,
rt-2
