### ISSUE TITLE
Large arrays slow compile time drastically

### ISSUE THREAD

**Issue by TommyB123** [pawn-lang/compiler#285]
Hey there.

I've been using noname's compiler for a while but decided to try this one to see how the recent speed optimizations compared. Originally, I noticed it wasn't nearly as fast but after removing [Crayder's model sizes include](https://github.com/Crayder/Model-Sizes-Plus), the speed of compilation is basically the same.

When using Sublime Text as an editor, this is the output.
With modelsizes `[Finished in 11.6s]`
Without modelsizes `[Finished in 2.7s]`

**Comment by maddinat0r** [comment]
The bottleneck is that for-loop in this function:
https://github.com/pawn-lang/compiler/blob/8c51b0bfd76d4ac84fc76dd01118c64135499cd4/source/compiler/sc1.c#L4975-L4983

Here's a quick patch to fix this (improved compile time from 13.5s to 1.3s in an empty script with the model sizes include):
```patch
From a6049c9bf39f8bc7de74d8bb98660fb978162fc3 Mon Sep 17 00:00:00 2001
From: Alex Martin <maddin4t0r@gmail.com>
Date: Fri, 9 Feb 2018 11:18:14 +0100
Subject: [PATCH] improve constvalue table appending performance

---
 source/compiler/sc1.c | 20 +++++++++++++++-----
 1 file changed, 15 insertions(+), 5 deletions(-)

diff --git a/source/compiler/sc1.c b/source/compiler/sc1.c
index b1ad703..9fd117f 100644
--- a/source/compiler/sc1.c
+++ b/source/compiler/sc1.c
@@ -163,6 +163,7 @@ static int sc_reparse = 0;      /* needs 3th parse because of changed prototypes
 static int sc_parsenum = 0;     /* number of the extra parses */
 static int wq[wqTABSZ];         /* "while queue", internal stack for nested loops */
 static int *wqptr;              /* pointer to next entry */
+static struct hashtable_t consttables_cache_ht;
 #if !defined SC_LIGHT
   static char sc_rootpath[_MAX_PATH];
   static char *sc_documentation=NULL;/* main documentation */
@@ -770,6 +771,7 @@ cleanup:
   delete_symbols(&glbtab,0,TRUE,TRUE);
   line_sym=NULL;
   hashtable_term(&symbol_cache_ht);
+  hashtable_term(&consttables_cache_ht);
   delete_consttable(&tagname_tab);
   delete_consttable(&libname_tab);
   delete_consttable(&sc_automaton_tab);
@@ -938,6 +940,7 @@ static void initglobals(void)
   glbtab.next=NULL;      /* clear global variables/constants table */
   loctab.next=NULL;      /*   "   local      "    /    "       "   */
   hashtable_init(&symbol_cache_ht, sizeof(symbol *),(16384/3*2),NULL); /* 16384 slots */
+  hashtable_init(&consttables_cache_ht,sizeof(constvalue*),256,NULL);
   tagname_tab.next=NULL; /* tagname table */
   libname_tab.next=NULL; /* library table (#pragma library "..." syntax) */
 
@@ -4974,12 +4977,16 @@ static constvalue *insert_constval(constvalue *prev,constvalue *next,const char
 
 SC_FUNC constvalue *append_constval(constvalue *table,const char *name,cell val,int index)
 {
-  constvalue *cur,*prev;
+  constvalue *new,*prev=hashtable_find(&consttables_cache_ht,(size_t)table);
+  if(prev==NULL) {
+    prev=table;
+  } else {
+    hashtable_remove(&consttables_cache_ht,(size_t)table);
+  }
 
-  /* find the end of the constant table */
-  for (prev=table, cur=table->next; cur!=NULL; prev=cur, cur=cur->next)
-    /* nothing */;
-  return insert_constval(prev,NULL,name,val,index);
+  new=insert_constval(prev,NULL,name,val,index);
+  hashtable_insert(&consttables_cache_ht,(size_t)table,new);
+  return new;
 }
 
 SC_FUNC constvalue *find_constval(constvalue *table,char *name,int index)
@@ -5029,6 +5036,9 @@ SC_FUNC void delete_consttable(constvalue *table)
 {
   constvalue *cur=table->next, *next;
 
+  if(hashtable_find(&consttables_cache_ht,(size_t)table))
+    hashtable_remove(&consttables_cache_ht,(size_t)table);
+
   while (cur!=NULL) {
     next=cur->next;
     free(cur);
-- 
2.16.1.windows.1

```

**Comment by Zeex** [comment]
While I agree that it's slow to compile, have you tried loading it at runtime? That file is not small (over 2 MB!), compiling it over and over seems like a waste of time because the compiler has to parse it each time and so on. Maybe it could also be converted from text to some binary form for faster loading.

**Comment by TommyB123** [comment]
I don't use that include anymore since the exact same data is provided in the ColAndreas plugin, which I recently started using. It does have an alternative version that uses an [SQLite database instead](https://github.com/Crayder/Model-Sizes-Plus/tree/db-mode), but it's obviously much slower when doing intensive operations during runtime (e.g, looping through all objects and adjusting their stream distance based on their model size). That's definitely an extreme case, but there's clear performance differences between having the data loaded into memory and reading it from a database. I'm sure there's other ways to parse the data, but those are the only options available for that particular include.

**Comment by Southclaws** [comment]
Would this speed improvement apply to uninitialised arrays or just arrays initialised with literal data? My survival gamemode still has an item table that's 20,000+ * ~1000 cells (multidimensional) - I know, I should be using dynamic memory from BigETI's plugin but still, it would be awesome to see that time cut down even more!

**Comment by Daniel-Cortez** [comment]
Already did pretty much the same kind of optimisation in #255, but in a different way: I saved the address of the last `constvalue` in the list into the list root element and just read it from there instead of looking it up in the hashtable at every call to `append_constval()`.

**Comment by TommyB123** [comment]
This is fixed as of the latest release so I'll go ahead and close it.
