### ISSUE TITLE
License compliance

### ISSUE THREAD

**Issue by samphunter** [pawn-lang/compiler#288]
**Is this a BUG REPORT, FEATURE REQUEST or QUESTION?**:

* [ ] Bug Report
* [ ] Feature Request
* [ ] Question
* [x] Other

**What happened**:

While discussing compatibility of Apache License with the License of this code, I noticed this code is not necessarily compliant with section/point 2 of the license:

> 2. Altered source versions must be plainly marked as such, and must not be misrepresented as being the original software.

While there is a mention of it in the readme, there is no mention in the license file or the source files (where the license headers are).

**What you expected to happen**:

In my opinion, a notice should be added into modified source files, that this is a modified version of the product to accommodate the license.

I would suggest something like:
This is a modified version of the software, maintained by the Compiler Team at https://github.com/pawn-lang/compiler. See the github repository for list of all modifications to the original source code and list of contributors.

**Comment by Daniel-Cortez** [comment]
The license only requires the modified code should be "plainly marked as such", but doesn't tell in which exact way it should be marked. And readme.md already says that the repo contains modified code
> This is a modified copy of the Pawn compiler version 3.2.3664 by Compuphase that fixes some bugs and adds a few features.

, so I'm sure this is enough to satisfy that requirement.

**Comment by samphunter** [comment]
Ok, I guess that is your decision. I would personally put it in the files, as that is where the license is located as well, and it would make it resilient to single files being used elsewhere.

**Comment by Jeroen52** [comment]
Could make a simple statement that the files have been modified from the original source.

**Comment by samphunter** [comment]
> What do you mean? I'm not a part of the team that manages this project, so I'm in no position to make any decisions here.

Oh? I thought you were part of the team. Others tagged you in some decision making situations and the Team link in the readme is broken, so I just assumed.
