### ISSUE TITLE
Separate resources files

### ISSUE THREAD

**Issue by EOussama** [pawn-lang/compiler#309]
**Is this a BUG REPORT, FEATURE REQUEST or QUESTION?**:

* [ ] Bug Report
* [X] Feature Request
* [ ] Question

**What you expected to happen**:
Define resources on separate files (preferably .xml files) and being able to reference them in pawn

Exactly like what Android's workflow is like, we should be able to have a separate XML file for every type of resources, for example, colors, we could have a file somewhere, probably in a folder called `values` named `colors.xml` inside of it like the following;

```xml
<!-- colors.xml -->

<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="white">0xFFFFFFFF</color>
    <color name="red">0xFF0000FF</color>
</resources>
```

```xml
<!-- strings.xml -->

<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="string_hello">Hello there, have a nice stay</string>
    <string name="string_goodbye">Goodbye, take care...</string>
</resources>
```

Then we could references those values like so;

```c
// something.pwn or something.inc

SendClientMessageToAll(@"colors/red", @"strings/string_hello");
```

Storing strings like that could really make it even easier to script multi-language scripts than using y_languages.

**Comment by Southclaws** [comment]
I don't think this belongs in the compiler. You can easily do this using existing tools - string templating is well trodden ground and there are a *lot* of tools that can do it. Most traditional server-rendered websites use some form of templating.

With sampctl too, you can add build plugins which perform commands prior to builds - that feature is pretty much designed to do template replacement on source files!
