### ISSUE TITLE
More warning when using compiler

### ISSUE THREAD

**Issue by qmnty** [pawn-lang/compiler#326]
Why this error / warning is showed when using pawn-lang compiler??

but when i'm using pawno compiler (old) it's normally function

> D:\Script\New Folder (15)\gamemodes\main.pwn(6210) : warning 208: function with tag result used before definition, forcing reparse
D:\Script\New Folder (15)\gamemodes\main.pwn(6238) : warning 208: function with tag result used before definition, forcing reparse
D:\Script\New Folder (15)\gamemodes\main.pwn(10016) : warning 208: function with tag result used before definition, forcing reparse
D:\Script\New Folder (15)\gamemodes\main.pwn(10035) : warning 208: function with tag result used before definition, forcing reparse
D:\Script\New Folder (15)\gamemodes\main.pwn(10055) : warning 208: function with tag result used before definition, forcing reparse
D:\Script\New Folder (15)\gamemodes\main.pwn(17891) : warning 208: function with tag result used before definition, forcing reparse
D:\Script\New Folder (15)\gamemodes\main.pwn(17925) : warning 208: function with tag result used before definition, forcing reparse
D:\Script\New Folder (15)\gamemodes\main.pwn(18988) : warning 208: function with tag result used before definition, forcing reparse
D:\Script\New Folder (15)\gamemodes\main.pwn(18997) : warning 208: function with tag result used before definition, forcing reparse
D:\Script\New Folder (15)\gamemodes\main.pwn(28722) : warning 208: function with tag result used before definition, forcing reparse
D:\Script\pawno\bin\include\foreach.inc(473) : error 021: symbol already defined: "Player@YSII_Cg"
D:\Script\pawno\bin\include\foreach.inc(477) : error 021: symbol already defined: "Bot@YSII_Cg"
D:\Script\pawno\bin\include\foreach.inc(764) : error 021: symbol already defined: "Itter_OPDCInternal"
D:\Script\pawno\bin\include\foreach.inc(840) : error 021: symbol already defined: "Itter_RandomInternal"
D:\Script\pawno\bin\include\foreach.inc(878) : error 021: symbol already defined: "Itter_FreeInternal"
D:\Script\pawno\bin\include\foreach.inc(907) : error 021: symbol already defined: "Itter_AddInternal"
D:\Script\pawno\bin\include\foreach.inc(941) : error 021: symbol already defined: "Itter_RemoveInternal"
D:\Script\pawno\bin\include\foreach.inc(964) : error 021: symbol already defined: "Itter_SafeRemoveInternal"
D:\Script\pawno\bin\include\foreach.inc(998) : error 021: symbol already defined: "Itter_ContainsInternal"
D:\Script\pawno\bin\include\foreach.inc(1017) : error 021: symbol already defined: "Itter_ClearInternal"
D:\Script\pawno\bin\include\foreach.inc(1042) : error 021: symbol already defined: "Itter_InitInternal"
D:\Script\pawno\bin\include\foreach.inc(1068) : error 021: symbol already defined: "Itter_PrevInternal"
D:\Script\pawno\bin\include\mSelection2.inc(849) : error 021: symbol already defined: "Itter_OnPlayerConnect"
D:\Script\pawno\bin\include\audio.inc(109) : error 021: symbol already defined: "Itter_OnGameModeInit"
D:\Script\pawno\bin\include\audio.inc(159) : error 021: symbol already defined: "Itter_OnPlayerDisconnect"
D:\Script\pawno\bin\include\a_http.inc(22) : error 021: symbol already defined: "HTTP"
D:\Script\pawno\bin\include\a_http.inc(22) : error 021: symbol already defined: "HTTP"
D:\Script\pawno\bin\include\YSI\internal\y_version.inc(194) : error 021: symbol already defined: "YVers_Callback"
D:\Script\pawno\bin\include\a_http.inc(22) : error 021: symbol already defined: "HTTP"
D:\Script\pawno\bin\include\YSI\internal\y_version.inc(122) : error 021: symbol already defined: "YVers_OnScriptInit"
D:\Script\pawno\bin\include\YSI\internal\y_version.inc(194) : error 021: symbol already defined: "YVers_Callback"
D:\Script\pawno\bin\include\YSI\internal\y_funcinc.inc(60) : error 021: symbol already defined: "_@_y_funcinc_@_"
D:\Script\pawno\bin\include\YSI/y_timers.inc(107) : error 021: symbol already defined: "YVers_OnScriptInit"
D:\Script\pawno\bin\include\YSI/y_timers.inc(226) : warning 209: function "YVers_OnScriptInit" should return a value
D:\Script\pawno\bin\include\a_http.inc(22) : error 021: symbol already defined: "HTTP"
D:\Script\pawno\bin\include\YSI\internal\y_version.inc(194) : error 021: symbol already defined: "YVers_Callback"
D:\Script\pawno\bin\include\a_http.inc(22) : error 021: symbol already defined: "HTTP"

Compilation aborted.

Pawn compiler 3.10.7	 	 	Copyright (c) 1997-2006, ITB CompuPhase

26 Errors.

Thanks in advance :)

**Comment by Jeroen52** [comment]
What flags and parameters are you using to compile?

**Comment by qmnty** [comment]
-r -w 203

**Comment by qmnty** [comment]
no flags

**Comment by Jeroen52** [comment]
You must be using some flags or parameters to compile the code. Else you'd get this.

```
Pawn compiler 3.10.7                    Copyright (c) 1997-2006, ITB CompuPhase

Usage:   pawncc <filename> [filename...] [options]

Options:
         -A<num>  alignment in bytes of the data segment and the stack
         -a       output assembler code
         -C[+/-]  compact encoding for output file (default=+)
         -c<name> codepage name or number; e.g. 1252 for Windows Latin-1
         -Dpath   active directory path
         -d<num>  debugging level (default=-d1)
             0    no symbolic information, no run-time checks
             1    run-time checks, no symbolic information
             2    full debug information and dynamic checking
             3    same as -d2, but implies -O0
         -e<name> set name of error file (quiet compile)
         -i<name> path for include files
         -l       create list file (preprocess only)
         -o<name> set base name of (P-code) output file
         -O<num>  optimization level (default=-O1)
             0    no optimization
             1    JIT-compatible optimizations only
             2    full optimizations
         -p<name> set name of "prefix" file
         -R[+/-]  add detailed recursion report with call chains (default=-)
         -r[name] write cross reference report to console or to specified file
         -S<num>  stack/heap size in cells (default=4096)
         -s<num>  skip lines from the input file
         -t<num>  TAB indent size (in character positions, default=8)
         -v<num>  verbosity level; 0=quiet, 1=normal, 2=verbose (default=1)
         -w<num>  disable a specific warning by its number
         -X<num>  abstract machine size limit in bytes
         -XD<num> abstract machine data/stack size limit in bytes
         -Z[+/-]  run in compatibility mode (default=-)
         -E[+/-]  turn warnings in to errors
         -\       use '\' for escape characters
         -^       use '^' for escape characters
         -;[+/-]  require a semicolon to end each statement (default=-)
         -([+/-]  require parantheses for function invocation (default=-)
         sym=val  define constant "sym" with value "val"
         sym=     define constant "sym" with value 0

Options with a value may optionally separate the value from the option letter
with a colon (":") or an equal sign ("="). That is, the options "-d0", "-d=0"
and "-d:0" are all equivalent.

```

**Comment by Jeroen52** [comment]
Please fill out this form, it shows up whenever you try to create an issue.

```
**Is this a BUG REPORT, FEATURE REQUEST or QUESTION?**:

* [ ] Bug Report
* [ ] Feature Request
* [ ] Question

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

* Operating System
* Compiler version
* How are you invoking the compiler? Pawno, Sublime, vscode, sampctl or command-line?
* If using sampctl, the version number

```

**Comment by YashasSamaga** [comment]
You may find this useful: https://ci.appveyor.com/project/Southclaws/compiler/build/53/artifacts

**Comment by Y-Less** [comment]
Yes that matters, that's an insanely old YSI version.

**Comment by qmnty** [comment]
Still not helped..

**Comment by qmnty** [comment]
So, how to solve these?

Should use the latest version of YSI?

**Comment by YashasSamaga** [comment]
You should use the latest version because the version you are using is very old and is mostly not maintained.

But I think this issue still stands since this compiler broke YSI 1.0 which was working in the old compiler.

**Comment by qmnty** [comment]
Another more warning & error

[https://pastebin.com/vPrGpddC](url)

**Comment by Y-Less** [comment]
Not a compiler issue, just poorly written code with old libraries and terribly named globals.
