### ISSUE TITLE
Wrong extension

### ISSUE THREAD

**Issue by NegativeIQ** [pawn-lang/compiler#329]
**Is this a BUG REPORT, FEATURE REQUEST or QUESTION?**:

* [x] Bug Report
* [ ] Feature Request
* [ ] Question

**What happened**:
Compiler generated file with wrong extension

**What you expected to happen**:
Expected to get .amx file instead i got .1

**How to reproduce it (as minimally and precisely as possible)**:
Include name followed by dot name and extension in you source file. For example `Test.1.pwn` and build.
**Anything else we need to know?**:

**Environment**:

* Operating System
Windows 7 SP1 x64
* Compiler version
3.10.7
* How are you invoking the compiler? Pawno, Sublime, vscode, sampctl or command-line?
Sublime (Southclaws pawn plugin), no sampctl at all
* If using sampctl, the version number

**Comment by YashasSamaga** [comment]
![capture](https://user-images.githubusercontent.com/6652578/42173288-2ed1e82c-7e3c-11e8-9fa6-c4101c8f33da.PNG)

I compiled a file named "Test.1.pwn" and got a "Test.1.amx" file.

Please check if this has something to do with your editor.

**Comment by NegativeIQ** [comment]
Yeah just tested with pawno and it works ok. Bug is only with Sublime build system.
@Southclaws will you take a look at it?
```
{
	"cmd": ["pawncc.exe", "$file", "-o$file_path/$file_base_name", "-;+", "-(+", "-d3"],
	"file_regex": "(.*?)\\(([0-9]*)[- 0-9]*\\)",
	"selector": "source.pwn",
	"working_dir": "C:/Samp Servers/Base Server/pawno/"
}
```

**Comment by Southclaws** [comment]
It's probably `$file_base_name`, that may be expanding to some incorrect value.

*or* `$file_base_name` expands to the actual filename and the bug lies in the `-o` flag.
