### ISSUE TITLE
array sizes do not match, or destination array is too small, but it happens since 3.10.7

### ISSUE THREAD

**Issue by juanpenia** [pawn-lang/compiler#331]
**Is this a BUG REPORT, FEATURE REQUEST or QUESTION?**:

* [ ] Bug Report (this, idk how to tick)
* [ ] Feature Request
* [ ] Question

**What happened**: I get an error regarding arrays that it didn't happen until I updated the compiler, today.

**What you expected to happen**: the code to compile as usual.

**How to reproduce it (as minimally and precisely as possible)**: I really don't know how to tell, there is a declared array on an include, used for a dialog, but when trying to compile it says: 
`dialogs.pwn(57) : error 047: array sizes do not match, or destination array is too small`

**Anything else we need to know?**: I can "fix" it raising the array size by 5 but it fucks up the dialogs in the gamemode, and this didn't use to happen before, I could perfectly compile it on 3.10.6 and older versions and the gamemode works well

**Environment**:

* Operating System: Windows 10 Pro x64.
* Compiler version: 3.10.7
* How are you invoking the compiler? Through [Notepad++](http://forum.sa-mp.com/showthread.php?t=174046)
* If using sampctl, the version number: -

**Comment by Y-Less** [comment]
I suspect I know what the issue is - use 3.10.6

**Comment by YashasSamaga** [comment]
@juanpenia Can you confirm if your issue was a duplicate of #307 ?

**Comment by juanpenia** [comment]
Yes, the same happens. I didn't check the other issues tho, my bad.

**Comment by Y-Less** [comment]
Wait, the same happens with 3.10.6?

**Comment by juanpenia** [comment]
No no, just in 3.10.7. I meant that I had the same problem than the person that posted the issue #307.
