### ISSUE TITLE
Hangs when a string define including an extended ascii table character (Windows-1252) gets processed inside an include

### ISSUE THREAD

**Issue by AGraber** [pawn-lang/compiler#350]
**Is this a BUG REPORT, FEATURE REQUEST or QUESTION?**:

* [x] Bug Report
* [ ] Feature Request
* [ ] Question

**What happened**:
Compiler hangs when trying to compile this:

test.pwn:
```pawn
#define crash "ñ"

#include "crash.pwn"

```

crash.pwn:
```pawn
crash
```
(yeah, only one line including "crash")

**What you expected to happen**:
Not hang, give an relevant error

**How to reproduce it (as minimally and precisely as possible)**:
Try to compile the files above encoded as Windows-1252

**Anything else we need to know?**:
The hanging happens whenever the compiler find a match for the `#define`, and starts eating up a good chunk of CPU (up to 28% on my PC).

`ñ` is a character outside of the normal ASCII table, just an example. It also crashes with `á`, `ö` and probably all other characters outside of the normal ASCII spec.

**Environment**:

* Operating System
Windows 10 Pro Build 17682

* Compiler version
Original SA-MP Compiler (2007), 3.10.8

* How are you invoking the compiler? Pawno, Sublime, vscode, sampctl or command-line?
`pawncc test.pwn`

**Comment by Zeex** [comment]
What compile flags do you use?

I did it like this:

```
pawncc "-(+" "-;+" -c1252 .\encoding_crash_gh_350.pwn
```

and there was no crash, only this error:

```
(0) : fatal error 108: codepage mapping file not found
```

Without `-c1252` it also didn't crash.

Maybe we are using different versions? I checked on 3.10.8 and 3.10.7.

**Comment by Zeex** [comment]
Still doesn't hang. I guess this has something to do with system settings. What code page does your command prompt use? You can check this by typing `chcp` without any parameters. Mine says `Active code page: 65001`.

**Comment by AGraber** [comment]
I tried a self-compiled 3.10.8 Debug build and there was a failed assertion:

![imagen](https://user-images.githubusercontent.com/18301034/44031832-871a7604-9f05-11e8-8689-aa224a835f80.png)

I don't find a way to debug the Release way, but probably this may point us in the right direction?

**Comment by kristoisberg** [comment]
Somewhat related to this: The comments in this [file](https://github.com/kristoisberg/samp-td-string-width/commit/82a5376a80bc87a640fec1a5e06fdd0f1ad622e9) got the compiler confused in a very strange way.

My code:
```
enum menuList {
    List<Map>:mItems,
    mPage,
    mStyle
};
static MenuList[MAX_PLAYERS][menuList];
```

Preprocessor output:
```
enum menuList {
    List@Map:mItems,
    mPage,
    mStyle
};
static MenuList[500][menuList];
```

The error:
```menulist.pwn:16 (error) expected token: "}", but found "<"```

Line 16 is `List<Map>:mItems,`. Both files were included to a main file, `List<Map>` is a PawnPlus macro, the compiler was invoked via sampctl.

**Comment by AGraber** [comment]
I've found that this doesn't happen at all when `NO_UTF8` is defined while building

**Comment by AGraber** [comment]
Both original and this compiler don't crash when the file containing `ñ` is encoded in correct UTF-8:

`crash.pwn(1) : error 010: invalid function or declaration`

**Comment by Y-Less** [comment]
I know SA:MP needs a codepage.  But the fact that a compiler compiled for UTF-8 doesn't work with non-UTF-8 characters isn't really a bug.

**Comment by Southclaws** [comment]
Possibly related to #181?

**Comment by AGraber** [comment]
Yes, it's a duplicate of #181, a 2 year old issue.
