### ISSUE TITLE
Pls change max len function name on 256, and not 31

### ISSUE THREAD

**Issue by GAwesoME** [pawn-lang/compiler#351]
I of course all understand... Mother-nature didn't reward you with big cocks... So you always specify a small number... BUT CAN MAKE THE MAXIMUM LENGTH OF A FUNCTION MORE THAN 31?

**Comment by Jeroen52** [comment]
This'll break compatibility with the official compiler.

**Comment by GAwesoME** [comment]
Rly? static enum does not violate compatibility, and it violates. just lmao

**Comment by MuhammadPawn** [comment]
Ты долбаёб блять?

**Comment by JustCup** [comment]
Stupid Russians got to us

**Comment by Y-Less** [comment]
1) If you want a feature, maybe don't insult people.

2) No, the function length is in the VM as well as the compiler, so it can't be changed without a SA-MP server update too.

**Comment by Y-Less** [comment]
3) New features aren't breaking compatibility - it is only when old features change, meaning that old code behaves differently, that it is a breaking change.
