### ISSUE TITLE
#pragma unused doesn't work

### ISSUE THREAD

**Issue by Zeex** [pawn-lang/compiler#354]
### Issue description:
Despite `#pragma unused v` this code still produced a "symbol is never used warning":

```pawn
f1(const &v) { }
f2(const ...) { }
f3(const v) {
	#pragma unused v
}
f4(...) { }
f5(v) {
	#pragma unused v
}
f6(&v) { }

main() {
	new a;
	f1(a);
	f2(a);
	f3(a);
	f4(a);
	f5(a);
	f6(a);
}
```

(It's from the `meaningless_class_specifiers_gh_172` test)

### Workspace Information:

* Compiler version: dev branch

**Comment by Zeex** [comment]
Maybe @YashasSamaga knows?

**Comment by YashasSamaga** [comment]
The warnings are correct. There is no `#pragma unused` for `f1` and `f6`. I think I forgot to add mark the symbols as unused in the test script.

**Comment by Zeex** [comment]
Yeah I'm totally blind, didn't see that those pragmas were in other functions
