### ISSUE TITLE
Inconsistent archive structure in 3.10.8

### ISSUE THREAD

**Issue by Southclaws** [pawn-lang/compiler#358]
The archive structure in 3.10.8 changed which caused sampctl users to experience errors while trying to use 3.10.8 - I actually fixed this by hand a few months ago by re-packaging the release assets but recently, for some reason, the release archives have reverted to the old structure (I have no idea how this happened).

So while I'll manually change it back, I'm opening an issue to bring this to everyone's attention and figure out why this happened.

1. Was 3.10.8 released by-hand, aka by manually zipping files?
2. If not, has the release archive generator script changed?
3. If it changed, why? Is it permanent? Do I need to make sampctl support two different release structures?

Another issue is that the `pawncc` files on Linux don't have the `x` permission bit set so the files aren't executable out-of-the-box - requiring user-intervention to run `chmod +x pawncc` - this may be a bit more tricky to fix in sampctl.

```bash
14:44 southclaws@corax /Users/southclaws/Desktop/pawn
% zipinfo pawnc-3.10.8-macos.zip
Archive:  pawnc-3.10.8-macos.zip
Zip file size: 117291 bytes, number of entries: 5
drwx---     6.3 fat        0 bx stor 18-Jun-30 16:42 bin/
-rw----     6.3 fat     8660 bx defN 18-Jun-30 16:42 bin/pawncc
-rw----     6.3 fat    21796 bx defN 18-Jun-30 16:42 bin/pawndisasm
drwx---     6.3 fat        0 bx stor 18-Jun-30 16:42 lib/
-rw----     6.3 fat   254920 bx defN 18-Jun-30 16:42 lib/libpawnc.dylib
5 files, 285376 bytes uncompressed, 116609 bytes compressed:  59.1%

14:44 southclaws@corax /Users/southclaws/Desktop/pawn
% zipinfo pawnc-3.10.6-macos.zip
Archive:  pawnc-3.10.6-macos.zip
Zip file size: 119935 bytes, number of entries: 5
drwxr-xr-x  2.0 unx        0 bx stor 17-Dec-31 12:46 pawnc-3.10.6-macos/bin/
-rwxr-xr-x  2.0 unx     8644 bX defN 17-Dec-31 12:46 pawnc-3.10.6-macos/bin/pawncc
-rwxr-xr-x  2.0 unx    21760 bX defN 17-Dec-31 12:46 pawnc-3.10.6-macos/bin/pawndisasm
drwxr-xr-x  2.0 unx        0 bx stor 17-Dec-31 12:46 pawnc-3.10.6-macos/lib/
-rwxr-xr-x  2.0 unx   255312 bX defN 17-Dec-31 12:46 pawnc-3.10.6-macos/lib/libpawnc.dylib
5 files, 285716 bytes uncompressed, 118875 bytes compressed:  58.4%
```

**Comment by Zeex** [comment]
I have no idea how this happened. I've just built packages from dev and from v3.10.8 on macOS and both archives had the correct structure.

**Comment by Zeex** [comment]
Packages are currently built on CI and uploaded to releases automatically after a new tag is created (see https://github.com/pawn-lang/compiler/wiki/Prepare-a-new-release). 

One could also build them manually but it's time consuming, although sometimes necessary, e.g. if there is some problem with CI configuration (outdated auth token, etc). For manual packaging there is a `package` target (or PACKAGE project in Visual Studio). I don't recall any recent changes to the packaging configuration, so this is pretty strange...

**Comment by Zeex** [comment]
Maybe @Y-Less knows? the release page says "Y-Less released this".

**Comment by Y-Less** [comment]
Yes, I wasn't sure how the releases were done and somewhat made it up as I went (which is why there are about 10 commits to that branch of my experimenting).  I think I did get it wrong slightly.  At this point the simplest solution is probably just to release 3.10.9 with no changes except a bumped version number and corrected package.

Sorry...

**Comment by Zeex** [comment]
Nah, it's ok, Southclaws has already fixed the archives. Thanks for confirming 👍

**Comment by nessa-blue** [comment]
a
