### ISSUE TITLE
Using ternary operator to output variable or string literal

### ISSUE THREAD

**Issue by kubkox3** [pawn-lang/compiler#362]
### Issue description:
I'm trying to use ternary operator inside format function, to output string dependant on whether global variable is empty or not, resulting in array must be indexed error (variable none).

### Minimal complete verifiable example (MCVE):
```
#include <a_samp>

enum E_ENUM
{
    E_ENUM_STRING[32]
}

static
	g_Variable[MAX_PLAYERS][E_ENUM]
;

main()
{
    new
        string[32]
    ;

    format(string, sizeof(string), "%s", g_Variable[0][E_ENUM_STRING][0] ? g_Variable[0][E_ENUM_STRING] : ("N/A"));
}
```

### Workspace Information:

* Compiler version: 3.10.8
* Command line arguments provided (or sampctl version): -
* Operating System: Windows 10

**Comment by Y-Less** [comment]
Because you're trying to use an enum element as an array, which they aren't.
