### ISSUE TITLE
Too much warnings issues

### ISSUE THREAD

**Issue by RaphaelCapone** [pawn-lang/compiler#379]
Hello there, I'm a newbie at pawn scripting. Recently I started to use this updated version of pawn compiler and I got alot of warnings like: warning 239: literal array/string passed to a non-const parameter,  warning 214: possibly a "const" array argument was intended: "array", etc
There are some examples:
```
[WARNING]:literal array/string passed to a non-const parameter
for
new string1[200];
format(string1, sizeof(string1), "/find /cancel find");
ShowPlayerDialog(playerid, DIALOG_HELP2, DIALOG_STYLE_MSGBOX, "SERVER: Job Commands", string1,"Back","Exit"); //here
```
 warning 214: possibly a "const" array argument was intended: "array"
for
```
new bool:_OAB_PlayerPlays[MAX_PLAYERS],
	_OAB_TICKS[MAX_PLAYERS],
	_OAB_CURRENT_TD_SLOT_1[MAX_PLAYERS],
	_OAB_CURRENT_TD_SLOT_2[MAX_PLAYERS], // here
	_OAB_CURRENT_TD_SLOT_3[MAX_PLAYERS],
	Text:_OAB_TD_SLOT_1[MAX_PLAYERS],
	Text:_OAB_TD_SLOT_2[MAX_PLAYERS],
	Text:_OAB_TD_SLOT_3[MAX_PLAYERS];
```
even on some YSI includes
```
include\YSI\y_debug.inc(395) : warning 239: literal array/string passed to a non-const parameter
public OnScriptInit()
{
	Debug_SetState();
	new
		s;
	// Test the ADDRESS of the variable, not the value.
	#emit CONST.pri YSI_FILTERSCRIPT
	#emit STOR.S.pri s
	if (s)
	{
		//goto Debug_OnScriptInit_no_fault();
		#if defined Debug_OnScriptInit
			return Debug_OnScriptInit();
		#else
			return 1;
		#endif
	}
	P:F("YSI_FILTERSCRIPT == 0"); //here
	while (s != 10000000) ++s;
	#emit CONST.pri 0
	#emit SCTRL     6
	return 1;
}
```

and so on.I got 2515 warnings when I compile with this version while with normal pawn compilator I got no warnings. Are these errors normal?Any solutions to hide em all or something?
Thanks a lot

**Comment by Y-Less** [comment]
https://github.com/pawn-lang/compiler/wiki/What's-new#const-correctness
https://github.com/pawn-lang/compiler/wiki/Const-Correctness
