### ISSUE TITLE
Constant arrays (2D, 3D and 4D) are modified without giving an error

### ISSUE THREAD

**Issue by George480** [pawn-lang/compiler#380]
### Issue description:

The expected behavior is an **error 022: must be lvalue (non-constant)**. However, it quietly modifies the constant array when it should not.

### Minimal complete verifiable example (MCVE):

```Pawn
#include <a_samp>

main()
{
    new arr[10][10];

    func(arr);

    printf("value: %d", arr[0][0]); // prints "value: 1"
}

func(const arr[][])
{
    arr[0][0] = 1;
}
```

### Workspace Information:

* Compiler version: **3.10.9**

**Comment by Y-Less** [comment]
I know I was the one who asked you to open an issue, and honestly thank-you for that (it is good to get more people involved here).  However, it turns out there already was one: https://github.com/pawn-lang/compiler/issues/322
