### ISSUE TITLE
`tagof()` as a tag.

### ISSUE THREAD

**Issue by Y-Less** [pawn-lang/compiler#384]
### Issue description:

Basically, allow variables to need to match in tag, even when the tag is unknown.  I'm not sure of the syntax, but I'm sure another one could be come up with.  Would work well with the any (`@`) tag for generic functions.

### Minimal complete verifiable example (MCVE):

```pawn
Func(@:a, tagof(a):b)
{
}

Func2({Float, Text}:a, tagof(a):b)
{
}

main()
{
    new Text:td;
    Func(4, 5); // No warning.
    Func(4.4, 5.5); // No warning.
    Func2(td, 5.5); // Warning, expected tag `Text` but found `Float` (despite both being valid).
}
```

### Workspace Information:

* Compiler version:
* Command line arguments provided (or sampctl version):
* Operating System:

**Comment by YashasSamaga** [comment]
What operator overloads should the compiler invoke?

Since there will be just one copy of the function, some operator has to be used but since the tag of `b` can vary, the compiler won't be able to generate the correct code unless it assumes the tag `b` to be fixed.

**Comment by Southclaws** [comment]
I suppose it could generate some simple branch code which is invoked based on a bit of runtime code which calls the correct overload. Is that a bit overkill?

This does look like a neat feature which would allow some neat generic functions.

**Comment by IllidanS4** [comment]
I would have a use for this feature in variadic functions that need a tag. For example, there's
```pawn
native List:list_new_args_t(TagTag:tag_id=tagof(arg0), AnyTag:arg0, AnyTag:...) = list_new_args;
#define list_new_args(%0) list_new_args_t(_,%0)
```
Which creates a list from elements, but only the tag of the first element is considered. Having variadic tagof would be the best, but it would be possible to rewrite the function in a safer way thanks to this:
```pawn
native List:list_new_args_t(TagTag:tag_id=tagof(arg0), AnyTag:arg0, tagof(arg0):...) = list_new_args;
```

**Comment by YashasSamaga** [comment]
@Southclaws what if there are 100 tags? 100 branches in the begining of the function?

**Comment by Y-Less** [comment]
You are right, that really wouldn't work.  I was only thinking about type-checking, I forgot about operator overloads.
