### ISSUE TITLE
Wiki: Const correctness

### ISSUE THREAD

**Issue by Jeroen52** [pawn-lang/compiler#391]
### Issue description:

There appears to be a mistype in the wiki page.
https://github.com/pawn-lang/compiler/wiki/Const-Correctness
There are two "Pass-By-Value".

### Fix
https://github.com/Jeroen52/pawn/wiki/Const-Correctness/_compare/a674c245163fab0f9e316f74ca8a067f5a8d27cd...f23195dcf5e53a60d0f08dee56a30f7fd9077885

Here is a .patch file.
[0001-I-spotted-Pass-By-Value-twice-I-m-pretty-damn-sure-t.txt](https://github.com/pawn-lang/compiler/files/2651467/0001-I-spotted-Pass-By-Value-twice-I-m-pretty-damn-sure-t.txt)

**Comment by Y-Less** [comment]
It's a wiki, anyone can edit it. If you find a bug it's much faster to just do it yourself than open an issue.

**Comment by Jeroen52** [comment]
I meant the wiki on GitHub, which I don't think I can edit.

Op do 6 dec. 2018 09:39 schreef Y-Less <notifications@github.com:

**Comment by Jeroen52** [comment]
I just checked and I can't edit the wiki, I would've done it if it were possible or me to do it.
