### ISSUE TITLE
Issue with first line of a .inc

### ISSUE THREAD

**Issue by LDami** [pawn-lang/compiler#400]
### Issue description:
I've just downloaded and installed the last release of the compiler (because I was still with the original one) and I tested to compile.
The compiler gives me the error:
_error 010: invalid function or declaration_
Always on the same include file, on the first line.
Actually the first line is: "#if defined _mysql_gesture_included" (which must not generated this error), but I can change, remove the line (and remove all the lines), the error still there.

### Minimal complete verifiable example (MCVE):
First case:
![capture](https://user-images.githubusercontent.com/30329760/50992096-84069b00-1516-11e9-9ac3-b8ced83b6647.PNG)
Second case:
![capture2](https://user-images.githubusercontent.com/30329760/50991821-dd21ff00-1515-11e9-8b3d-f710a3d14403.PNG)
These 2 conditions are generating me the same errors. Check the capture below:
![capture3](https://user-images.githubusercontent.com/30329760/50991883-03479f00-1516-11e9-8926-1d28b34ff5dd.PNG)

All the "undefined symbol" error is due to my lib file causing the error.

### Workspace Information:

* Compiler version: 3.10.9
* Command line arguments provided (or sampctl version): -r -w 203
* Operating System: Windows 10

**Comment by Southclaws** [comment]
This is likely a [Byte Order Mark](https://en.wikipedia.org/wiki/Byte_order_mark).

I'd advise against using Pawno as it doesn't handle encoding (or anything for that matter). If you open the file in a modern editor such as Notepad++, Sublime Text or Visual Studio Code it should automatically detect the encoding settings using the BOM. You can then opt to re-encode the file back to UTF-8 or another ANSI codepage.

**Comment by LDami** [comment]
It was that ... SImply ..
I'm sorry for the useless (not) issue !
I convert my lib to UTF-8 (without BOM) and it works !

Thanks for your help.
Damien.
