### ISSUE TITLE
const static

### ISSUE THREAD

**Issue by samphunter** [pawn-lang/compiler#410]
### Issue description:

`static const` is resolved as a constant value (in memory) and can't be used to initialize an array. `const static` gives an error. I would suggest `const static` to be a static constant, that can be optimized away by the compiler. Would be nice to be able to create it somehow.

### Minimal complete verifiable example (MCVE):

```
static const mSize = 10;
new array[mSize]; // error 008: must be a constant expression; assumed zero
```

```
const static mSize = 10; // error 020: invalid symbol name ""
new array[mSize];
```

### Workspace Information:

* Compiler version: 3.10.9
* Command line arguments provided (or sampctl version): `-;+", "-(+`
* Operating System: Windows 8.1

**Comment by Y-Less** [comment]
I'm not sure how to delete you.  Sorry.
