### ISSUE TITLE
using this compiler

### ISSUE THREAD

**Issue by omcho420** [pawn-lang/compiler#414]
### Issue description:
Well this is not an issue this is a question so, how to use this compiler on linux?

Can you give me a step-by-step tutorial or something like that

edit: also I don't have anything related to pawn downloaded except the default samp server package for linux

Thanks for the help in advance and sorry for making an "issue" for this

```
```

### Workspace Information:

* Compiler version:
* Command line arguments provided (or sampctl version):
* Operating System:

**Comment by omcho420** [comment]
I mean whenever I try to run this
"pawncc "-;+" "-(+" -i:../pawno/include grandlarc.pwn -d3 -Z -E"
I get "pawncc: command not found"

**Comment by YashasSamaga** [comment]
Where have you put the `pawncc` executable?

You can either add that directory to `PATH` or specify the full path to the compiler. The latter is the better solution especially if you are using an IDE.

**Comment by Southclaws** [comment]
Also keep in mind the compiler is a 32 bit application and will require you to enable 32 bit execution on your OS.

**Comment by omcho420** [comment]
> Also keep in mind the compiler is a 32 bit application and will require you to enable 32 bit execution on your OS.

I did that, and now I get this
- https://imgur.com/a/EvHQ8hI

**Comment by Jeroen52** [comment]
Run: chmod +x libpawnc.so

Then run it again.

**Comment by omcho420** [comment]
> Run: chmod +x libpawnc.so Then run it again.

Same thing again

- https://i.imgur.com/JDHemBM.png

**Comment by Zeex** [comment]
Try `LD_LIBRARY_PATH=$PWD ./pawncc` or put libpawnc.so in a system-wide lib directory which ld knows about (/usr/lib, /usr/local/lib, etc) and run `sudo ldcache`.

**Comment by omcho420** [comment]
> Try `LD_LIBRARY_PATH=$PWD ./pawncc`

This works, thanks, even tho it gives me errors for unused stuff but it compiles atleast, thanks again
