### ISSUE TITLE
Which one

### ISSUE THREAD

**Issue by NemanjaMAX** [pawn-lang/compiler#418]
Which file I need to edit to modify this:
```
Pawn compiler 3.10.9	 	 	Copyright (c) 1997-2006, ITB CompuPhase

Header size:          13216 bytes
Code size:          1931516 bytes
Data size:         18820476 bytes
Stack/heap size:      16384 bytes; estimated max. usage=3936 cells (15744 bytes)
Total requirements:20781592 bytes
```
Thank u <3

**Comment by Y-Less** [comment]
Modify what?

**Comment by NemanjaMAX** [comment]
Output, I want to add some ASCII for fun xD
Like:
Pawn compiler 3.10.9	 	 	Copyright (c) 1997-2006, ITB CompuPhase
ASCII ART GOES HERE BIIISCH

**Comment by Jeroen52** [comment]
Perhaps this'll help you.
https://github.com/pawn-lang/compiler/blob/0f2bd0b282e84e3d6af5f38581ff48738374b6ca/source/compiler/sc1.c#L1460

**Comment by NemanjaMAX** [comment]
Thank you!
