### ISSUE TITLE
Compiler for Mac OS Catalina

### ISSUE THREAD

**Issue by Chesterfiels** [pawn-lang/compiler#430]
Unfortunately the new Mac OS Catalina has stopped supporting 32-bit programs. Maybe because of this compiler has stopped working (error: Bad CPU type in executable)

I can't build compiler in XCode

**Comment by Y-Less** [comment]
I've said this before, and I'll say it again.

The job of an OS is to abstract hardware and provide features to run programs with.  If your OS doesn't provide the features and abstractions you need to run your programs, or the OS developers decide they know better than you about what programs you should be running, the OS has failed in its primary job.  It can look as flashy as it likes, but that doesn't solve the fundamental issue.

Thus, by the most basic definition of "operating system" yours is a bad operating system.  Use a good one.  By which I mean any one that allows you to run the programs you want to run.

**Comment by Southclaws** [comment]
Side note: this is nothing to do with the OS, it's XCode. Just install XCode 9.x and you can build 32 bit applications.
