### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by MakiPL1** [pawn-lang/compiler#467]
C:\Users\PC\Desktop\Server\gamemodes\RPG.pwn(972) : error 001: expected token: "-string end-", but found "-identifier-"
C:\Users\PC\Desktop\Server\gamemodes\RPG.pwn(972) : error 001: expected token: "-string end-", but found "-identifier-"
C:\Users\PC\Desktop\Server\gamemodes\RPG.pwn(972) : warning 215: expression has no effect
C:\Users\PC\Desktop\Server\gamemodes\RPG.pwn(972) : error 001: expected token: ";", but found "-integer value-"
C:\Users\PC\Desktop\Server\gamemodes\RPG.pwn(972) : fatal error 107: too many error messages on one line

Compilation aborted.Pawn compiler 3.2.3664	 	 	Copyright (c) 1997-2006, ITB CompuPhase

4 Errors.

**Comment by Y-Less** [comment]
That's not a compiler bug.

**Comment by Southclaws** [comment]
From the template you deleted while writing your issue:

> Please ensure that your issue is directly related to the pawn-lang/compiler. Issues
seeking help with scripting or doubts about SA-MP are not relevant to this project.
