### ISSUE TITLE
Undefined array

### ISSUE THREAD

**Issue by MassonNN** [pawn-lang/compiler#473]
### Issue description:

 There is a problem in which the Zeex compiler, as well as the standard just crashes. I would like this bug to be fixed :).

### Minimal complete verifiable example (MCVE):

```
#define MAX

new IsItMax[MAX];
```

### Workspace Information:

* Compiler version: zeex mod.
* Command line arguments provided (or sampctl version): -
* Operating System: windows 7

**Comment by Y-Less** [comment]
![image](https://user-images.githubusercontent.com/991078/71046365-5bc8e880-2138-11ea-935e-6010d00de16a.png)

Worked fine for me.
