### ISSUE TITLE
Throw warning when modifying/accessing char array with [] instead of {}

### ISSUE THREAD

**Issue by 0x416c69** [pawn-lang/compiler#474]
It can go terribly wrong when you access it using []

**Comment by Y-Less** [comment]
It can go wrong, but any wrong code will go wrong.  However, this is not syntactically incorrect, nor is it always logically incorrect.  Your use of it like that might be wrong (which is unfortunate), but that's not a general rule that should be enforced by the compiler.

**Comment by 0x416c69** [comment]
Well, here we need warning levels and suppression. Because this **has** to be a warning, but a high level one.

**Comment by Y-Less** [comment]
No, it doesn't.  There is nothing technically wrong with accessing different arrays in different ways.  `char` just means `/4` (rounded up).  It's just a numeric operator like `+ 3`.

**Comment by 0x416c69** [comment]
Believe me, I know what it is and I know what does it do.

But what is the point of declaring a char array and access/modify four byte of it at once? Even if it has to be a thing it should throw a high level warning, it usually doesn't make any sense. (It could be the coder's possible mistake in 99% of the situation) You shouldn't try to push a 4 byte value to a 1 byte allocated variable.

If 99% of people wants to manipulate their char array using [], they would go with a normal pawn cell manipulation and allocation.

In cpp, you get warnings or you have to go with a cast to do that:
```cpp
__int8 variable[64];
variable[0] = 512l; // warning C4305 in MSVC, warning in clang: implicit conversion from 'int' to 'char' changes value from 512 to 0
// Workaround: This long bad boy "reinterpret_cast<__int32*>(variable)[0] = 2 ^ 9;" (C: "((__int32*)variable)[0] = 2 ^ 9;"), it's not just a simple {} which can cause ambiguity and semantic errors
```

In PAWN:
```c
new variable[32], charArray[32 char];
variable{0} = 512; // No warnings
charArray[0] = 1; // As PAWN doesn't have endian problem (thank god) and is big endian: charArray{3} = 1, charArray{2} = 0, charArray{1} = 0, charArray{0} = 0
```

In none of popular languages it isn't implemented at all or it cannot be easily manipulated by just a simple {} or similar. (Both statically and dynamically typed languages)

It shouldn't be a thing at all to access a char array using [] (CompuPhase didn't put enough time on it initially and I know types aren't separated, but allocation type should be implemented and it should be separated and throw a toggleable warning just for the backward compatibility sake)
