### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by OnixGame** [pawn-lang/compiler#477]
hello

when i was compiling my gm with pawncc ,i got this error (but the include is already in pawno/include folder):

Pawn compiler 3.10.9	 	 	Copyright (c) 1997-2006, ITB CompuPhase

gamemodes/COD3.pwn(5) : fatal error 100: cannot read from file: "a_samp"

Compilation aborted.

how can i fix it ?
a_samp
core.inc
are already in pawno/include
Ubuntu 18

**Comment by Zorono** [comment]
are you running sampctl ??
and please show us how you are including them... eg: `#include <......>`
