### ISSUE TITLE
Nested paths are relative to the entry pwn file where they should be relative to the file they are being included by

### ISSUE THREAD

**Issue by EOussama** [pawn-lang/compiler#478]
Hello;

The compiler behaves weirdly and impractically when nested inclusion is at hand.
Take the following folder tree for example;

![Annotation 2020-01-26 171311](https://user-images.githubusercontent.com/22644543/73138091-254b8b00-405f-11ea-90c4-dff82b2e329c.jpg)

Here's the inclusion process

The `main.pwn` file
```pwn
#include "./core/core"
```

The `core.inc` file
```pwn
#include "./player/player"
```

The compiler raises an error in the `core.inc` file as the inclusion path is somewhat faulty, because apparently, all inclusion paths, no matter how deeply nested they are, are relative to `main.pwn`.
A workaround for this issue at the moment is to ditch `#include "./player/player"` for `#include "./core/player/player"`.

It would be more convenient if these paths are adjusted to being relative to the file they are being included by.

**Comment by EOussama** [comment]
**Side note**: This problem was met while using sampctl;

```json
  "user": "eoussama",
  "repo": "eo-san-andreas-survival",
  "entry": "./src/main.pwn",
  "output": "./gamemodes/main.amx",
  "dependencies": ["sampctl/samp-stdlib"],
  "runtime": {
    "hostname": "EO San Andreass Survival",
    "gamemodetext": "Survival, DayZ",
    "mapname": "San Andreas",
    "language": "English",
    "maxplayers": 32,
    "announce": true,
    "port": 7777,
    "rcon_password": "admin",
    "gamemodes": ["main"]
  }
}
```

I don't know about the non-sampctl use-case though.

**Comment by Y-Less** [comment]
It's not that simple.  They change where they are relative to based on compiler flags, versions, and directory separator.  See this link for way more information:

https://github.com/pawn-lang/compiler/wiki/File-Inclusion

The other problem is that changing it is a breaking change, and that just introduces MORE ways that paths are interpreted.  There's already code that looks like this to deal with it:

https://github.com/pawn-lang/YSI-Includes/blob/5.x/YSI_Coding/y_hooks.inc#L109
