### ISSUE TITLE
Ternary operator bug

### ISSUE THREAD

**Issue by tr1xy** [pawn-lang/compiler#481]
### Issue description:

Ternary operator returns `error 033: array must be indexed (variable "-unknown-")` on enum data types.

### Minimal complete verifiable example (MCVE):

```
enum E_SOME_ENUM
{
    it_is_a_string_i_swear[50]
};
new SomeEnum[E_SOME_ENUM];

new string[50];

// Error 033
format(string, sizeof(string), "%s", isnull(SomeEnum[it_is_a_string_i_swear] == false ? SomeEnum[it_is_a_string_i_swear] : "null");

// Works
ormat(string, sizeof(string), "%s", isnull(SomeEnum[it_is_a_string_i_swear] == false ? "some string" : "null");
```

EDIT: Both are strings, just other is stored in different data type, I think it should be supported.

### Workspace Information:

* Compiler version: 3.10.9
* Command line arguments provided (or sampctl version):
```
{
    "selector": "source.pwn",
    "working_dir": "C:\\Compiler",
    "cmd": [
        "pawncc.exe",
        "$file",
        "-o$file_path/$file_base_name",
        "-;+",
        "-(+",
        "-d3",
        "-Z+",
        "-iC:\\Compiler\\include"
    ],
    "file_regex": "(.*?)\\(([0-9]*)[- 0-9]*\\)"
}
```
* Operating System: Windows 10

@ADRFranklin

**Comment by Romz24** [comment]
`isnull(SomeEnum[it_is_a_string_i_swear] == false`
change to
`isnull(SomeEnum[it_is_a_string_i_swear]) == false`

**Comment by Y-Less** [comment]
Those aren't strings.  Those are enum slots, which are totally different, just look similar.
