### ISSUE TITLE
include with YSI "\" cannot read from file

### ISSUE THREAD

**Issue by MateusArthur** [pawn-lang/compiler#483]
My build sublime
> {
	"cmd": ["/bin/pawncc", "$file", "-i/home/mateus/Documentos/BPV-Android/pawno/include", "-(+", "-;+"]
}

fatal error 100: cannot read from file: "YSI_Data\y_iterate"

if I change the '\' to '/' it works, but it stops working on windows

**Comment by Y-Less** [comment]
Well the other paths are `/` in the cmd, so that needs changing to `\` on Windows.
