### ISSUE TITLE
Run time error 18: "File is for a newer version of he AMX"

### ISSUE THREAD

**Issue by tr1xy** [pawn-lang/compiler#489]
### Issue description:

This happens when I enable **-O2** option.
### Minimal complete verifiable example (MCVE):

```
```

### Workspace Information:

* Compiler version: 3.10.10
* Command line arguments provided (or sampctl version):
```
{
    "selector": "source.pwn", 
    "file_regex": "(.*?)\\(([0-9]*)[- 0-9]*\\)", 
    "working_dir": "C:/Compiler", 
    "cmd": [
        "pawncc.exe", 
        "$file", 
        "-o$file_path/$file_base_name",
        "-;+", 
        "-(+",
        "-O2",
        "-d2"
    ]
}
```
* Operating System: W10

How can I fix this?

**Comment by Daniel-Cortez** [comment]
SA-MP can't run code compiled with `-O2` as it uses an older version of the interpreter; use `-O1` or `-O0` instead.

**Comment by Y-Less** [comment]
> How can I fix this?

Don't use `-O2`.  Unfortunately this isn't a compiler issue.
