### ISSUE TITLE
Crashes the compiler

### ISSUE THREAD

**Issue by Romz24** [pawn-lang/compiler#490]
### Issue description:
Instead of throwing an error, the compiler just crashes.

### Minimal complete verifiable example (MCVE):

```
static const anim_libs[2/*wrong size*/][9] =
{
	"BAR",
	"BASEBALL",
	"BEACH"
};
```

### Workspace Information:

* Compiler version: 3.10.10

**Comment by vsergeenko777** [comment]
Possibly related to #486 and #439

**Comment by YashasSamaga** [comment]
duplicate of #439
