### ISSUE TITLE
Big Problem

### ISSUE THREAD

**Issue by TerzicScript** [pawn-lang/compiler#492]
So i switched from Windows to Ubuntu, so i started using this compiler. The gamemode compiled fine, no errors, no warnings, but few things started happening. First, half of the stuff disappeared, textdraws, commands, pickups, vehicles... After restart, the mod is not loading at all, File Or Function is not found..
So i read the server_log hoping i will find problem. All plugins loaded fine, everything is up to date and i tried using older versions of the compiler but still nothing.. 

Hope someone has solution.. If you need more info, i will happily provide them in order to solve this problem..

**Comment by sampwide** [comment]
download sublime and build it natively through it

**Comment by TerzicScript** [comment]
Can you explain me how? I am new to all this,,

пон, 17. феб 2020. у 18:28 sampwide <notifications@github.com> је
написао/ла:

**Comment by Y-Less** [comment]
It could be an issue with include paths.  Do you have files with the same name in different directories?  They behave very oddly.

**Comment by Y-Less** [comment]
@AmyrAhmady just mentioned something about this.  The fact that the server can't find the script implies it didn't actually compile.  If you get no warnings or errors it could be that something is silently failing or crashing when building.  So you actually aren't getting the compilation done, but it isn't telling you that.  Or you're compiling with `-l` or `-a`.

**Comment by YashasSamaga** [comment]
@TerzicScript have you solved it or isolated the problem?

**Comment by TerzicScript** [comment]
Solved it by installing windows..
