### ISSUE TITLE
literal array/string warnings...

### ISSUE THREAD

**Issue by flexmaster4** [pawn-lang/compiler#493]
### Issue description:

So I used pawn compiler version 3.10.8 and everything was alright. I have downloaded new version(3.10.10) and when I tried to compile my script I got 6k+ warnings:
### Minimal complete verifiable example (MCVE):

```
```

### Workspace Information:

* Compiler version: 3.10.10
* Command line arguments provided (or sampctl version):
* Operating System: Win10x64

**Comment by flexmaster4** [comment]
D:\LocalServer\pawno\include\nex-ac.inc(2468) : warning 214: possibly a "const" array argument was intended: "button2"
D:\LocalServer\pawno\include\nex-ac.inc(2468) : warning 214: possibly a "const" array argument was intended: "button1"
D:\LocalServer\pawno\include\nex-ac.inc(2468) : warning 214: possibly a "const" array argument was intended: "info"
D:\LocalServer\pawno\include\nex-ac.inc(2468) : warning 214: possibly a "const" array argument was intended: "caption"
D:\LocalServer\pawno\include\nex-ac.inc(3569) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(3579) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(3590) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(3630) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(3784) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(3904) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(3941) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(4001) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(4017) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(4122) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(4158) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(4255) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(4265) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(4386) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(4425) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(4458) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(4530) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(4559) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(4593) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(4628) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(4667) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(4705) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(4733) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(4760) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(4786) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(4809) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(4833) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(4860) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(4912) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(4954) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(4987) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5001) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5018) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5046) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5073) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5100) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5137) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5160) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5175) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5201) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5221) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5246) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5260) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5283) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5321) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5341) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5366) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5386) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5414) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5444) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5473) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5490) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5506) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5524) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5546) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5582) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5606) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5622) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5645) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5665) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5698) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5938) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(5952) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6012) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6061) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6150) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6311) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6342) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6375) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6408) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6423) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6431) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6444) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6456) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6464) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6478) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6486) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6517) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6557) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6572) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6590) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6620) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6655) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6785) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6797) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6823) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6839) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6860) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6880) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6898) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6918) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(6939) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(7013) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(7028) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(7068) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(7070) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(7693) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(7728) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(7751) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(7772) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(7818) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(7987) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(8027) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(8115) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(8128) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(8166) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(8261) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(8277) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(8338) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(8396) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(8430) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(8453) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(8486) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(8503) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(8516) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(8536) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(8565) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(8587) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(8615) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(8645) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\nex-ac.inc(9094) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\mSelection.inc(133) : warning 214: possibly a "const" array argument was intended: "button_text"
D:\LocalServer\pawno\include\mSelection.inc(154) : warning 214: possibly a "const" array argument was intended: "header_text"
D:\LocalServer\pawno\include\mSelection.inc(311) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\mSelection.inc(312) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\mSelection.inc(313) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\mSelection.inc(355) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\mSelection.inc(356) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\mSelection.inc(357) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\mSelection.inc(325) : warning 214: possibly a "const" array argument was intended: "items_array"
D:\LocalServer\pawno\include\eSelection.inc(129) : warning 214: possibly a "const" array argument was intended: "items"
D:\LocalServer\pawno\include\eSelection.inc(129) : warning 214: possibly a "const" array argument was intended: "header"
D:\LocalServer\pawno\include\weapon-config.inc(1524) : warning 214: possibly a "const" array argument was intended: "animname"
D:\LocalServer\pawno\include\weapon-config.inc(1524) : warning 214: possibly a "const" array argument was intended: "animlib"
D:\LocalServer\pawno\include\weapon-config.inc(1777) : warning 214: possibly a "const" array argument was intended: "text"
D:\LocalServer\pawno\include\weapon-config.inc(1890) : warning 214: possibly a "const" array argument was intended: "string"
D:\LocalServer\pawno\include\weapon-config.inc(1914) : warning 214: possibly a "const" array argument was intended: "text"
D:\LocalServer\pawno\include\weapon-config.inc(2031) : warning 214: possibly a "const" array argument was intended: "string"
D:\LocalServer\pawno\include\weapon-config.inc(3120) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(3120) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(3349) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(3349) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4781) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4781) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4783) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4783) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4789) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4789) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4791) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4791) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4796) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4796) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4806) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4806) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4809) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4809) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4813) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4813) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4816) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4816) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4820) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4820) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4822) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4822) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4824) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4824) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4828) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4828) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4830) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4830) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4833) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4833) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4835) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4835) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4837) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4837) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4839) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\weapon-config.inc(4839) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\progress2.inc(351) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\progress2.inc(357) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\progress2.inc(363) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\progress2.inc(370) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\progress2.inc(376) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\progress2.inc(382) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\progress2.inc(389) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\progress2.inc(395) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\progress2.inc(401) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\progress2.inc(408) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\progress2.inc(414) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\progress2.inc(420) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\pawno\include\geolocation.inc(287) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(5851) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(6661) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(6704) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(6878) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(6908) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(6957) : warning 214: possibly a "const" array argument was intended: "description"
D:\LocalServer\gamemodes\myscript.pwn(6957) : warning 214: possibly a "const" array argument was intended: "name"
D:\LocalServer\gamemodes\myscript.pwn(6998) : warning 214: possibly a "const" array argument was intended: "money_sign"
D:\LocalServer\gamemodes\myscript.pwn(6998) : warning 214: possibly a "const" array argument was intended: "menuid"
D:\LocalServer\gamemodes\myscript.pwn(7150) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7163) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7208) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7411) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7414) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7416) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7429) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7432) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7434) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7505) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7508) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7510) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7589) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7593) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7594) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7599) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7601) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7604) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7613) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7617) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7618) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7623) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7625) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7628) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7637) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7641) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7642) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7647) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7649) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7652) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(7884) : warning 214: possibly a "const" array argument was intended: "ime"
D:\LocalServer\gamemodes\myscript.pwn(8069) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(8069) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(8087) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(8087) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(8123) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(8123) : warning 239: literal array/string passed to a non
D:\LocalServer\gamemodes\myscript.pwn(109851) : warning 239: literal array/string passed to a non-const parameter
D:\LocalServer\gamemodes\myscript.pwn(109862) : warning 239: literal array/string passed to a non-const parameter
Pawn compiler 3.10.10	 	 	Copyright (c) 1997-2006, ITB CompuPhase

Header size:          42340 bytes
Code size:         14894172 bytes
Data size:         64495692 bytes
Stack/heap size:      16384 bytes; estimated max. usage=4310 cells (17240 bytes)
Total requirements:79448588 bytes

6133 Warnings.

**Comment by Y-Less** [comment]
That's correct.

**Comment by Daniel-Cortez** [comment]
Not exactly on topic, but I think one of the biggest pitfalls (if not the biggest one) in release 3.10.10 is that warning 239 was re-enabled for native functions, which means that the users are now required to use the [modified SA-MP includes](https://github.com/sampctl/samp-stdlib/releases), otherwise they'll get a lot of new warning 239 messages.
@Y-Less, maybe it would make sense to add a note about this on the [release page](https://github.com/pawn-lang/compiler/releases/tag/v3.10.10) (along with a link to the includes) for convenience?

**Comment by flexmaster4** [comment]
How can I fix this for 6k+ lines...?

**Comment by Y-Less** [comment]
https://github.com/pawn-lang/compiler/wiki/What's-new#const-correctness

https://github.com/pawn-lang/compiler/wiki/Const-Correctness

**Comment by flexmaster4** [comment]
Yeah, I know but I have so much lines. Is there any regex syntax or fast workaround. I have this even in updated includes but 6000 it's too much...

**Comment by Y-Less** [comment]
6000 really isn't that much.  Anyway, you'll find that fixing a single function will often remove multiple warnings because they're all calls to that same function.
