### ISSUE TITLE
`error 025: function heading differs from prototype` counts names

### ISSUE THREAD

**Issue by Y-Less** [pawn-lang/compiler#495]
### Issue description:

I don't think the names of parameters should be taken in to account for this error, only the "shape" - tags, `const`, array, etc.

### Minimal complete verifiable example (MCVE):

```
forward MyFunc(a);

public MyFunc(b)
{
}
```

The two prototypes are entirely compatible, why is this an error?

### Workspace Information:

* Compiler version:
* Command line arguments provided (or sampctl version):
* Operating System:

**Comment by Daniel-Cortez** [comment]
This was probably a deliberate choice from the original developer of Pawn, as this language was designed for beginners and different argument names in function prototypes/headings could confuse them.

Anyway, if you want to remove this restriction, this can be done by removing/commenting out a couple of lines in `argcompare()`:
https://github.com/pawn-lang/compiler/blob/4ede5aa24f5203b0b4c5ace9f5285c5784683959/source/compiler/sc1.c#L3913-L3914

**Comment by Y-Less** [comment]
That is true.  It will help with say parameters in the wrong order.
