### ISSUE TITLE
Q: How to make gate that closes after 5 sec?

### ISSUE THREAD

**Issue by Kreyren** [pawn-lang/compiler#497]
### Issue description:

DISCLAIMER: I wasn't able to find the solution in documentation assuming `SetTimer()` does not seem to work and provided examples using `settime` seem outdated.

Requesting more information to https://github.com/Kreyren/KSGFSAMP/blob/a3b363d771b8134fecdb2469785933923d6e3339/src/main.pwn#L182 where is seems that compiler skips the `MoveObject()` call if the previous `MoveObject()` call was used in the same function. -> Possible bug or pebcak?

Note that i've learned the syntax today (i have background in CS) and i am working on this on community request.

### Workspace Information:

* Compiler version: 1.0 (Tried to update on 3.8.8 which does not have pawno.exe)
* Command line arguments provided (or sampctl version): Does not know
* Operating System: Windows 10

**Comment by EOussama** [comment]
How does this co-relate to the compiler?

**Comment by Kreyren** [comment]
@EOussama The compiler is used to compile this script/program where the call is not in affect after previous call has been used -> Based on available info i deduced that being either compiler bug or peback and so i am requesting more info to continue my work.

**Comment by Kreyren** [comment]
PSA: Solved in https://github.com/Kreyren/KSGFSAMP/commit/aa55f6faed506e895127e76e9f04af4c8f563faa
