### ISSUE TITLE
enum 2d

### ISSUE THREAD

**Issue by JoaquinZc** [pawn-lang/compiler#516]
### Issue description:

Hi, I have only a simple question, i don't know if this issues exists, but.. is it possible make enums with two dimensions? or am i need use #define for that? (sorry my english)

### Minimal complete verifiable example (MCVE):

```
static enum enum_info
{
	object_modelid,
	object_name[SERVER_MAX_LANGUAGES][35], // <- error compiler.
	object_amount,
	ITEM_ACTIONS: object_actions,
	object_changes[5],
	object_text[30]
};

```

### Workspace Information:

* Compiler version: I'm use sampctl 1.8.39
* Command line arguments provided (or sampctl version): "args": ["-;+", "-(+", "-d3", "-Z+"]
* Operating System: windows 8.1 x64

**Comment by Y-Less** [comment]
No
