### ISSUE TITLE
Missing operator call after compound assignment operator (+=, -=, ...)

### ISSUE THREAD

**Issue by Shiska** [pawn-lang/compiler#517]
### Issue description:

The assigment operator isn't called for a tag mismatch after a compound assignment operator
If the tag matches or if a constant value, maybe other further cases I didn't check

If I am not mistaken this also didn't work in the old compiler so it is a pretty old bug I guess maybe it was fixed in any newer pawn version

### Minimal complete verifiable example (MCVE):

```
stock Tag: operator=(oper) {
    return Tag: oper;
}

stock operator+(Tag: oper1, Tag: oper2) {
    return (_: oper1 + _: oper2);
}

stock operator+(Tag: oper1, oper2) {
    return (_: oper1 - _: oper2);
}

main() {
    new Tag: t1, Tag: t2;
    // calls Tag: operator=(oper) after addition
    t1 = t1 + t2; // operator+(Tag:, Tag:)
    t1 = t1 + 5; // operator+(Tag:, _:)
    t1 += _: t2; // operator+(Tag:, _:)
    // does not call Tag: operator=(oper) after addition
    t1 += t2; // operator+(Tag:, Tag:)
    t1 += 5; // operator+(Tag:, _:)
}
```

### Workspace Information:

* Compiler version: 3.10.10
* Command line arguments provided (or sampctl version): sampctl version 1.8.39
* Operating System: Windows

**Comment by Daniel-Cortez** [comment]
Thanks for reporting this! I'm almost done with a PR that fixes this bug.
Also, while experimenting with the fix, I found another bug related to this issue:
```Pawn
#pragma option -a

stock Tag:operator=(oper)
{
	return Tag:oper;
}

stock operator+(Tag:oper1, oper2)
{
	return (_:oper1 - _:oper2);
}

main()
{
	new Tag:t1, Tag:t2;
	t1 = (t1 += _:t2);
}
```
This code generates the following assembly for function `main()`:
```
	proc	; main
	; line 34
	; line 35
	;$lcl t1 fffffffc
	push.c 0
	;$exp
	;$lcl t2 fffffff8
	push.c 0
	;$exp
	; line 36
	load.s.pri fffffff8
	load.s.alt fffffffc
	push.pri
	push.alt
	;$par
	push.c 8
	call .40000003+0	; operator+(Tag:,_:)
	push.pri
	;$par
	push.c 4
	call .40000003=0	; Tag:operator=(_:)
	stor.s.pri fffffffc
	push.pri
	;$par
	push.c 4
	call .40000003=0	; Tag:operator=(_:)
	stor.s.pri fffffffc
	;$exp
	stack 8
	zero.pri
	retn
```
Note that `Tag:operator=(_:)` is called twice: the first time it's for `(t1 += _:t2)`, which is correct, but the second time it's for `t1 = (...)`, which is wrong because the result of the previous operation (`+=`) should have tag `Tag:`, not `_:`.
