### ISSUE TITLE
warning 214 when using decrement of an array cell

### ISSUE THREAD

**Issue by KarpovVyacheslav** [pawn-lang/compiler#536]
### Issue description:

If you use the decrement of an array cell with assignment to a variable, this will generate a warning 214 ("possibly a "const" array argument was intended: "array"").

### Minimal complete verifiable example (MCVE):

```pawn
new g_Array[3];

main()
{
    func(g_Array[0]);
}

stock func(array[])//warning 214
{
    new value = --array[0];

    //or
    new value2 = array[0]--;
}
```
If you try to define the array-argument as constant, it will give an error 22 (must be lvalue (non-constant))
### Workspace Information:

* Compiler version: 3.10.9, 3.10.10
* Command line arguments provided (or sampctl version):
* Operating System: Windows 10 ver 1909 (build 18363.900)

**Comment by Daniel-Cortez** [comment]
Fixed in #537.
@pawn-lang Close?
