### ISSUE TITLE
`#assert` doesn't work without debug mode

### ISSUE THREAD

**Issue by Daniel-Cortez** [pawn-lang/compiler#542]
### Issue description:

https://github.com/pawn-lang/compiler/blob/29770ae31b0a47ae4767d2fdfb979643e2309e4b/source/compiler/sc2.c#L1118-L1119
Apparently, `#assert` only works when runtime checks for array bounds are enabled (note the `(sc_debug & sCHKBOUNDS)!=0` check in the above code). In other words, it works with `-d1`, `-d2` and `-d3`, but it doesn't work with `-d0`.
Does anyone know why it works that way? Because I see no logical connection between a preprocessor directive and runtime checks.

I suspect the original Pawn author intended to use the `(sc_debug & sCHKBOUNDS)!=0` check for operator `assert()`, not for the directive.

### Minimal complete verifiable example (MCVE):

See above.

### Workspace Information:

* Compiler version: 3.10.10, 3.2.3664
* Command line arguments provided (or sampctl version):
* Operating System:

**Comment by Y-Less** [comment]
I suspect you're right, is `assert()` also gated?

**Comment by Daniel-Cortez** [comment]
Yes, it is.
https://github.com/pawn-lang/compiler/blob/29770ae31b0a47ae4767d2fdfb979643e2309e4b/source/compiler/sc1.c#L6045

**Comment by Daniel-Cortez** [comment]
Fixed in #544.
