### ISSUE TITLE
Assignments to constant multidimensional arrays are not prevented

### ISSUE THREAD

**Issue by Daniel-Cortez** [pawn-lang/compiler#553]
### Issue description:

The following code compiles, although normally the compiler should print an error as the destination array is constant.
```Pawn
main()
{
    new const a[1][1];
    a[0][0] = 0;
}
```

### Minimal complete verifiable example (MCVE):

See above.

### Workspace Information:

* Compiler version: 3.2.3664, 3.10.10
* Command line arguments provided (or sampctl version):
* Operating System:

Special thanks to user [DeimoS](https://pro-pawn.ru/member.php?u=2548) from the pro-pawn.ru forums who originally discovered this bug.

**Comment by Daniel-Cortez** [comment]
Hmm, that's strange. I wanted to close this issue, as it should've been fixed in #554, but decided to double-check, and after building the compiler from the `dev` branch, the example code from the 1'st post still compiles without errors.

**Comment by Daniel-Cortez** [comment]
And it seems that the changes from that PR are not present in `dev` either.
@Y-Less, you probably closed #554, but accidentally skipped it while merging it along with the other PRs.

**Comment by Y-Less** [comment]
https://github.com/pawn-lang/compiler/commit/1ec20337f72a8b9712e13c2448a8713215e6fb0e

**Comment by Y-Less** [comment]
Unless it got somehow reverted by another commit.

**Comment by Y-Less** [comment]
At least some of it seems to still be there:

https://github.com/pawn-lang/compiler/blob/dev/source/compiler/sc1.c#L2259-L2263
https://github.com/pawn-lang/compiler/blob/dev/source/compiler/sc1.c#L2397-L2402
https://github.com/pawn-lang/compiler/blob/dev/source/compiler/tests/gh_553.meta
https://github.com/pawn-lang/compiler/blob/dev/source/compiler/tests/gh_553.pwn

**Comment by Daniel-Cortez** [comment]
Well, this is embarassing... It seems that when I pulled the changes from the `dev` branch, they didn't get pulled into my local repo for some reason. Not sure what it was, but now everything works correctly, so sorry for bothering.

I'll close this now.
