### ISSUE TITLE
State func crash the compiler.

### ISSUE THREAD

**Issue by Dayvison** [pawn-lang/compiler#557]
### Issue description:
Expected:
`(error) function heading differs from prototype`
but crashes the compiler

### Minimal complete verifiable example (MCVE):

```
stock f(a[]) <b:A> {}
stock f(b[]) <b:B> {}
```

### Workspace Information:

* Compiler version:
* Command line arguments provided (or sampctl version):
* Operating System:

**Comment by Daniel-Cortez** [comment]
Fixed in #561.
@pawn-lang Close?
