### ISSUE TITLE
Variable type tags ??

### ISSUE THREAD

**Issue by Zorono** [pawn-lang/compiler#562]
Whyn't add the ability to manage many more types of Variable Tags like `String:`

for example: https://github.com/50DKP/FF2-Official/blob/131a2d5272f8dc953c89fef9f93abe08558668d4/addons/sourcemod/scripting/freak_fortress_2/default_abilities.sp#L86

**Comment by Y-Less** [comment]
You can define any tags you like any time.  They aren't set by the compiler.
