### ISSUE TITLE
Bad CPU type in executable

### ISSUE THREAD

**Issue by renatochic69** [pawn-lang/compiler#563]
### Minimal complete verifiable example (MCVE):

Is there any way to run the compiler on macOS Catalina? I really liked the workflow it had with Visual Studio Code.

### Workspace Information:

* Compiler version: 3.10.10
* Command line arguments provided (or sampctl version): N/A
* Operating System: macOS Catalina

**Comment by alexchester** [comment]
Any solutions?

**Comment by Y-Less** [comment]
Yes:

> An operating system is a program that abstracts computer hardware and allows you to run the software you want. If an OS can't run the software you want to run it is, by definition, a BAD operating system; regardless of how white and shiny it looks while refusing to do things.

Stop using an objectively bad OS.
