### ISSUE TITLE
Inaccurate optimisation of triadic calls.

### ISSUE THREAD

**Issue by Y-Less** [pawn-lang/compiler#96]
Example:

``` pawn
new x = y ? (func(), 7) : 9;
```

I would expect this code, if `y` was true, to call `func()`, execute any side-effects it has, then assign `7` to `x`, just like this (with `func()` potentially being a non-value-returning function):

``` pawn
new x;
if (y)
{
    func();
    x = 7;
}
else
{
    x = 9;
}
```

However, it seems that the compiler actually completely removes the call to `func()` as if it was never needed.  If that call does important global state modifying things, that's bad.

**Comment by YashasSamaga** [comment]
The problem can be generalized:

For any expression of the form `(expr1, expr2, expr3, ...)`, the compiler erases the generated code as it moves to the next expression in the chain blatantly ignoring side effects.

`new y = (x++, 5);`

The increment never happens.
